version: '3'
services:
  api:
    build: ./E-Library-API
    ports:
      - 5000:80
    environment: 
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - sqlserver
    links: 
      - "sqlserver:sqlserver"
      
  sqlserver:
    build: ./SQL
    ports:
      - 1433:1433
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Test12345678
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    volumes:
      - sql-volume:/var/opt/mssql
  
  frontend:
    build: ./E-Library-Frontend
    ports:
      - 80:80
volumes:
  sql-volume: